<#
.SYNOPSIS
    Runs VBA macro from hardware.xlsm AND the backend with the same barcode,
    then byte-compares the .prn outputs.

.PARAMETER Barcode
    Single barcode to test (overrides test-cases.json)

.PARAMETER KeepFiles
    Keep .prn files after comparison (default: delete)

.PARAMETER ExcelVisible
    Show Excel window during VBA execution (default: $false)

.EXAMPLE
    .\scripts\Compare-VbaAndBackend.ps1

.EXAMPLE
    .\scripts\Compare-VbaAndBackend.ps1 -Barcode 'K"žSV" 603684 010'
#>
param(
    [string]$Barcode = "",
    [switch]$KeepFiles,
    [switch]$ExcelVisible
)

$ErrorActionPreference = "Stop"
$RepoRoot = "D:\Projects\paperless\paperless_backend"
$WorkbookPath = Join-Path $RepoRoot "hardware_test.xlsm"
$TestCasesPath = Join-Path (Join-Path $RepoRoot "test-fixtures") "test-cases.json"
$VbaOutputDir = "C:\temp\excel_vs_backend"
$BackendOutputDir = Join-Path (Join-Path $RepoRoot "test-fixtures") "output"
$RunnerScript = Join-Path (Join-Path $RepoRoot "scripts") "generate-single-prn.ts"

foreach ($d in $VbaOutputDir, $BackendOutputDir) {
    if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
}

# Load barcodes
$barcodes = @()
if ($Barcode) {
    $barcodes = @($Barcode)
} elseif (Test-Path $TestCasesPath) {
    $raw = Get-Content $TestCasesPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $barcodes = $raw | ForEach-Object {
        if ($_ -is [string]) { $_ } else { $_.barcode }
    }
} else {
    Write-Host "ERROR: test-cases.json not found and no -Barcode given" -ForegroundColor Red
    exit 1
}

Write-Host ("=" * 75)
Write-Host "  VBA vs Backend Comparison"
Write-Host ("  Barcodes: " + $barcodes.Count)
if ($ExcelVisible) { Write-Host "  Excel: VISIBLE" }
Write-Host ("=" * 75)

$results = @()

foreach ($bc in $barcodes) {
    Write-Host ("`n" + ("-" * 75))
    Write-Host ("  Barcode: " + $bc)
    Write-Host ("-" * 75)

    $salesOrder = $bc.Substring($bc.Length - 10, 6)
    $nameBase = ($bc.Substring($bc.Length - 10) -replace ' ', '_')

    # === PHASE 1: Run VBA ===
    Write-Host "  [1/3] Running VBA macro..."
    Get-ChildItem $VbaOutputDir -Filter "*.prn" | Remove-Item -Force -ErrorAction SilentlyContinue

    $vbaSuccess = $false
    $vbaPrnPath = $null
    $vbaSize = 0

    try {
        Write-Host "  Opening Excel..."
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $ExcelVisible
        $excel.DisplayAlerts = $false
        $excel.ScreenUpdating = $false

        # Use a fresh temp copy for each test to avoid Databaze bloat
        $tempWbPath = [System.IO.Path]::GetTempFileName() + ".xlsm"
        Copy-Item $WorkbookPath $tempWbPath -Force
        Write-Host ("  Temp copy: " + (Split-Path $tempWbPath -Leaf))

        $wb = $excel.Workbooks.Open($tempWbPath)
        Write-Host "  Workbook opened"

        # Unprotect Hlavni sheet and clear Databaze (temp copy may have residuals)
        $wsHlavni = $wb.Sheets("Hlavni")
        $wsHlavni.Unprotect()
        $wsDB = $wb.Sheets("Databaze")
        $wsDB.Cells.ClearContents()

        # Set barcode
        $wsHlavni.Range("C30").Value2 = ""
        $wsHlavni.Range("C15").Value2 = ""
        Start-Sleep -Milliseconds 200
        $wsHlavni.Range("C15").Value2 = $bc
        Write-Host ("  Barcode set")

        Write-Host "  Running hlavni..."
        $excel.Run("hlavni")
        Write-Host "  hlavni completed"
        Start-Sleep -Seconds 2

        $wb.Close($false)
        $excel.Quit()

        Write-Host ("  Checking for .prn in " + $VbaOutputDir)
        $prns = Get-ChildItem $VbaOutputDir -Filter "*.prn" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending
        Write-Host ("  Found " + $prns.Count + " .prn files")
        if ($prns) {
            $vbaPrnPath = $prns[0].FullName
            $vbaSize = $prns[0].Length
            Write-Host ("  VBA .prn: " + (Split-Path $vbaPrnPath -Leaf) + " (" + $vbaSize + " bytes)") -ForegroundColor Cyan
            $vbaSuccess = $true
        } else {
            Write-Host "  [WARN] No .prn generated by VBA" -ForegroundColor Yellow
        }
    } catch {
        $msg = $_.Exception.Message
        Write-Host ("  [ERROR] VBA execution: " + $msg) -ForegroundColor Red
        if ($msg -match "VBProject|Trust|method.*Run") {
            Write-Host "  TIP: Macros must be enabled in hardware.xlsm" -ForegroundColor Yellow
        }
    } finally {
        # Clean up temp workbook
        if ($tempWbPath -and (Test-Path $tempWbPath)) {
            Remove-Item $tempWbPath -Force -ErrorAction SilentlyContinue
        }
        if ($excel) {
            try { $excel.Quit() } catch {}
            [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
        }
        # Force-kill any lingering Excel process
        Get-Process EXCEL -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        [GC]::Collect()
        [GC]::WaitForPendingFinalizers()
        Start-Sleep -Milliseconds 500
    }

    if (-not $vbaSuccess) {
        Write-Host "  [SKIP] No VBA output" -ForegroundColor Yellow
        continue
    }

    # Copy VBA .prn to output dir with barcode-based name
    $vbaNamedPath = Join-Path $BackendOutputDir ($nameBase + "_excel.prn")
    Copy-Item $vbaPrnPath $vbaNamedPath -Force
    Write-Host ("  Copied VBA .prn → " + (Split-Path $vbaNamedPath -Leaf)) -ForegroundColor Cyan
    # Remove original from temp dir (ugly random name)
    Remove-Item $vbaPrnPath -Force -ErrorAction SilentlyContinue
    $vbaPrnPath = $vbaNamedPath

    # === PHASE 2: Run backend ===
    Write-Host "  [2/3] Running backend..."

    $backendOutPath = Join-Path $BackendOutputDir ($nameBase + "_backend.prn")
    Push-Location $RepoRoot
    $env:BARCODE = $bc
    $Node = "C:\Users\matej\node-v24.3.0-win-x64\node.exe"
    & $Node -r ts-node/register $RunnerScript $backendOutPath 2>$null
    Pop-Location

    if (-not (Test-Path $backendOutPath)) {
        Write-Host "  [ERROR] Backend failed" -ForegroundColor Red
        continue
    }

    $backendSize = (Get-Item $backendOutPath).Length
    Write-Host ("  Backend .prn: " + (Split-Path $backendOutPath -Leaf) + " (" + $backendSize + " bytes)") -ForegroundColor Green

    # === PHASE 3: Compare ===
    Write-Host "  [3/3] Comparing..."

    $vbaBytes = [System.IO.File]::ReadAllBytes($vbaPrnPath)
    $backendBytes = [System.IO.File]::ReadAllBytes($backendOutPath)

    function Normalize-LF($bytes) {
        $out = New-Object System.Collections.Generic.List[byte]
        $i = 0
        while ($i -lt $bytes.Length) {
            if ($i -lt $bytes.Length - 1 -and $bytes[$i] -eq 0x0D -and $bytes[$i+1] -eq 0x0A) {
                $out.Add(0x0A)
                $i += 2
            } else {
                $out.Add($bytes[$i])
                $i++
            }
        }
        return $out.ToArray()
    }

    $vbaNorm = Normalize-LF $vbaBytes
    $backendNorm = Normalize-LF $backendBytes

    $enc = [System.Text.Encoding]::GetEncoding(28591)
    $vbaText = $enc.GetString($vbaNorm)
    $backendText = $enc.GetString($backendNorm)

    $vbaLines = $vbaText -split "`n"
    $backendLines = $backendText -split "`n"

    Write-Host ("  VBA:     " + $vbaLines.Length + " lines / " + $vbaBytes.Length + " bytes")
    Write-Host ("  Backend: " + $backendLines.Length + " lines / " + $backendBytes.Length + " bytes")

    $diffCount = 0
    $maxLines = [Math]::Max($vbaLines.Length, $backendLines.Length)
    $diffLines = @()

    for ($i = 0; $i -lt $maxLines; $i++) {
        $v = if ($i -lt $vbaLines.Length) { $vbaLines[$i] } else { $null }
        $b = if ($i -lt $backendLines.Length) { $backendLines[$i] } else { $null }
        if ($v -ne $b) {
            $diffCount++
            if ($diffCount -le 20) {
                $diffLines += ("  DIFF line " + $i)
                $diffLines += ("    VBA:     " + $v)
                $diffLines += ("    Backend: " + $b)
            }
        }
    }

    if ($diffLines.Count -gt 0) {
        foreach ($dl in $diffLines) {
            Write-Host $dl -ForegroundColor Yellow
        }
    }

    if ($diffCount -eq 0) {
        Write-Host "  *** IDENTICAL ***" -ForegroundColor Green
    } else {
        Write-Host ("  *** " + $diffCount + " DIFFERENCES ***") -ForegroundColor Red
    }

    $results += @{
        Barcode    = $bc
        SalesOrder = $salesOrder
        VbaLines   = $vbaLines.Length
        BackendLines = $backendLines.Length
        VbaBytes   = $vbaBytes.Length
        BackendBytes = $backendBytes.Length
        Diffs      = $diffCount
        VbaPrn     = $vbaPrnPath
        BackendPrn = $backendOutPath
        Identical  = ($diffCount -eq 0)
    }

    if (-not $KeepFiles) {
        Remove-Item $vbaPrnPath -Force -ErrorAction SilentlyContinue
    }
}

# Summary
Write-Host ("`n" + ("=" * 75))
Write-Host "  SUMMARY"
Write-Host ("=" * 75)

$allOk = $true
foreach ($r in $results) {
    if (-not $r.Identical) { $allOk = $false }
    $icon = if ($r.Identical) { " OK " } else { "DIFF" }
    $color = if ($r.Identical) { "Green" } else { "Red" }
    Write-Host ("  [" + $icon + "] " + $r.Barcode) -ForegroundColor $color
    Write-Host "         VB: lines=$($r.VbaLines) bytes=$($r.VbaBytes)  BK: lines=$($r.BackendLines) bytes=$($r.BackendBytes) diffs=$($r.Diffs)" -ForegroundColor $color
}

if ($allOk -and $results.Count -gt 0) {
    Write-Host ("`n  *** ALL " + $results.Count + " TESTS PASSED ***") -ForegroundColor Green
    if ($KeepFiles) {
        Write-Host "`n  Saved files:" -ForegroundColor Yellow
        foreach ($r in $results) {
            Write-Host ("    " + $r.BackendPrn) -ForegroundColor Yellow
            Write-Host ("    " + $r.VbaPrn) -ForegroundColor Yellow
        }
    } else {
        foreach ($r in $results) {
            Remove-Item $r.BackendPrn -Force -ErrorAction SilentlyContinue
        }
    }
} elseif ($results.Count -eq 0) {
    Write-Host "`n  No tests executed." -ForegroundColor Yellow
} else {
    Write-Host "`n  Some tests failed." -ForegroundColor Red
}

Write-Host ("=" * 75)
